### ISSUE TITLE
[TASK] Create the filter page and display all of the content of the database

### ISSUE THREAD

**Issue by asha97** [programer653/SOEN341-teamproject4#30]
This is where we are going to be placing all of the products of the database, as well as a box in the side bar in which we are going to be filtering by category.

**Comment by pavithrasiv** [comment]
@asha97 How is it going with viewing products on the filtering page?

**Comment by asha97** [comment]
I was able to display it! Would you like me to close the issue? @pavithrasiv

**Comment by pavithrasiv** [comment]
perfect, I'll close it now then!
