### ISSUE TITLE
Epic User Story 4: Search Bar

### ISSUE THREAD

**Issue by pavithrasiv** [programer653/SOEN341-teamproject4#39]

**Comment by asha97** [comment]
implementation has been done, but there are bugs

**Comment by asha97** [comment]
in home.js, there is the front end and the back end code, but there are bugs 

Here is a snippet of the code:
    const inputSearch = (event) => {
        const data1 = event.target.value;
        setSearch(data1);
        setProducts(products.filter((product) =>
        products.itemName.toLowerCase().includes(search.toLowerCase())
        ))
    };
