### ISSUE TITLE
[User Story]: As an admin, I want to add product so that other users can view them on the browsing page 

### ISSUE THREAD

**Issue by programer653** [programer653/SOEN341-teamproject4#8]

**Comment by pavithrasiv** [comment]
The admin can add products, however images that they add are not being displayed, fill fix this

**Comment by asha97** [comment]
ok let me know if you need help! @pavithrasiv

**Comment by pavithrasiv** [comment]
alright if everything looks good, I'll close the issue now!

**Comment by pavithrasiv** [comment]
closing this issue, products can be added by the admin
